from ListNode import SinglyLinkedList
new_linked_list = SinglyLinkedList()
print("Outping the insert at the end method \n")
new_linked_list.insert_at_end(5)
new_linked_list.insert_at_end(10)
new_linked_list.insert_at_end(15)
new_linked_list.insert_at_end(20)
new_linked_list.insert_at_end(25)
new_linked_list.insert_at_end(30)
new_linked_list.output_list()
print("-------------------------\n")
print("Testing the length methods \n")
print(f'The length of the list  is:   {new_linked_list.length_of_list()}')
new_linked_list.output_list()
print()
print("-------------------------\n")
print("Testing search method \n")
print(f'Seraching for the value 5:{new_linked_list.unordered_search(5)}')
print(f'Searching for the value 15:{new_linked_list.unordered_search(15)}')
new_linked_list.output_list()
print()
print("-------------------------\n")
print("Testing  the remove at the end method \n")
print("Original list")
new_linked_list.output_list()
print()
print("Output after removing the last element {30} at the end")
new_linked_list.remove_list_item_by_id(new_linked_list.length_of_list()-1)
new_linked_list.output_list()
print()
print("Output after removing the item with id_2 ")
new_linked_list.remove_list_item_by_id(2)
new_linked_list.output_list()
print()
print("Output after removing the item with id_0 ")
new_linked_list.remove_list_item_by_id(0)
new_linked_list.output_list()
print()
print("-------------------------")

print("Testing  Inserting Items at the start")
print("The first Original list")
new_linked_list.output_list()
print()
print("Output After inserting item at the start")
new_linked_list.insert_at_start(4)
new_linked_list.insert_at_start(3)
new_linked_list.insert_at_start(2)
new_linked_list.insert_at_start(1)
new_linked_list.output_list()
print()
print("-------------------------\n")
print("Testing  Inserting Items after another item")
print("The first Original list")
new_linked_list.output_list()

new_linked_list.insert_after_item(4,5)
new_linked_list.insert_after_item(5,6)
new_linked_list.insert_after_item(6,7)
new_linked_list.insert_after_item(7,8)
new_linked_list.insert_after_item(8,9)
new_linked_list.insert_after_item(9, 10)
new_linked_list.insert_after_item(10, 11)
                                  
print("After Insertion")
print()
new_linked_list.output_list()
print()
print("-------------------------\n")
print("Testing  Inserting Items before another item")
print("The first Original list")
new_linked_list.output_list()
new_linked_list.insert_before_item(25,24)
new_linked_list.insert_before_item(21,20)
new_linked_list.insert_before_item(23,22)
new_linked_list.insert_before_item(24,23)
print()
print("After Insertion")
new_linked_list.output_list()
print()
print("-------------------------\n")
print("Testing  Inserting an item at Specific Index")
print("The first Original list")
new_linked_list.output_list()

new_linked_list.insert_at_index(0,"A")
new_linked_list.insert_at_index(1,"B")
new_linked_list.insert_at_index(2,"C")
new_linked_list.insert_at_index(3,"D")
print()
print("After Insertion")
new_linked_list.output_list()
print()
print("-------------------------\n")
print("Testing  Deleting from the Start")
print("Before Deletion")
new_linked_list.output_list()
new_linked_list.remove_at_start()
new_linked_list.insert_at_end(26)

print("After Deletion deleted ")
new_linked_list.output_list()
print()
print("-------------------------\n")
print("Testing Deleting at the end")
print("The first Original list")
new_linked_list.output_list()
print()
print("Before Deletion")
new_linked_list.remove_at_end()
print("After Deletion")
new_linked_list.output_list()
print()
print("-------------------------\n")
print("Testing Deleting by Value")
print("The first Original list")
new_linked_list.output_list()
print("Before Deletion")
new_linked_list.delete_by_value(23)
print("After Deleting the value  23")
new_linked_list.output_list()
print()
print("-------------------------\n")
print("Sorting the elements in ascending order")

new_linked_list.sortlist()
print("After Sorting")
new_linked_list.output_list()
print()
print("-------------------------\n")
print("Test to merge sorted list")
other_list = SinglyLinkedList()
other_list.insert_at_end(5)
other_list.insert_at_end(6)
other_list.insert_at_end(7)
other_list.insert_at_end(8)
other_list.insert_at_end(9)
print("Merging the elements")
merge_list= new_linked_list.merge_sorted(other_list)
merge_list.output_list()
print()
print("-------------------------\n")
print("Testing Extend Method")
new_linked_list.extend(other_list)
new_linked_list.output_list()